language: java
sudo: false

jdk:
  - oraclejdk8


branches:
  only:
    - master

################
## Note the "&&". We want the script to fail fast if there is a technical error (javadoc, style)
## which saves time both for travis but also for developers looking at the error logs.
## Moreover,  if the script makes it to  mvn -f ./jmh/pom.xm, then **all** previous
## tests must be green.
#################
script: mvn javadoc:test-javadoc &&  mvn clean test jacoco:report install -Dgpg.skip=true

after_success:
  - mvn coveralls:report
